const express = require('express');
const router = express.Router();
const axios = require('axios')
let API_KEY =""

const isLoggedOut = require("../middleware/isLoggedOut");
const isLoggedIn = require("../middleware/isLoggedIn");

// GET /user-profile
router.get("/profile", isLoggedIn, (req, res) => {
    res.render("profile");
});

router.get('/profile/:username',isLoggedIn, (req,res)=>{
    const {username} = req.params; 
    console.log('username', username)
    User.findOne({username})
        .then(x =>{
            console.log('user', x)
            res.render('profile',{x})
        })
    
})


//Axios Call to create a User to be able to use the API services
let createUserConfig = {
    method: 'post',
    url: 'http://api.cup2022.ir/api/v1/user',
    headers: 
        "Content-Type: application/json"
        ,
    data: { //replace Date here by your personal information
        "name" : `${process.env.API_NAME}`,
        "email": `${process.env.API_EMAIL}`,
        "password": `${process.env.API_PASS}`,
        "passwordConfirm" : `${process.env.API_PASS}`
    }
};

//To Log In with Email and Password on the API => response will give back a Token to access all the APIs services, this token is autogenerated every time you login
let loginUserConfig = {
    method: 'post',
    url: 'http://api.cup2022.ir/api/v1/user/login',
    headers: "Content-Type: application/json",
    data: { //replace Date here by your personal information
        "email": `${process.env.API_EMAIL}`,
        "password": `${process.env.API_PASS}`
    }
};

//To send a GET request to API using the token from login
let tokenAcessGETConfig = {
    method:'get',
    headers: `Authorization : Bearer ${API_KEY}`
}



//Display all the Information on the incoming Matches on the "MATCHES.HBS" file
router.get("/matches", async (req, res, next) => {
    await axios(loginUserConfig)
        .then (data=>{
            console.log(API_KEY)
            API_KEY = data.data.data.token
            return API_KEY 
            //console.log(API_KEY)
  })
    await axios("http://api.cup2022.ir/api/v1/match",  {
        method:'get',
        headers: `Authorization : Bearer ${API_KEY}`
    })
        .then( matchesData =>{
            let matchesInfo = matchesData.data.data
            console.log(matchesInfo[2])
            res.render('matches/matches', {matchesInfo})    
        
        })
        console.log(API_KEY)
});

router.post('/matches/:id/predict', async (req,res)=>{
    let id = req.params.id
    await axios(loginUserConfig)
    .then (data=>{
        console.log(API_KEY)
        API_KEY = data.data.data.token
        return API_KEY 
        //console.log(API_KEY)
})
    await axios(`http://api.cup2022.ir/api/v1/match/${id}`,  {
        method:'get',
        headers: `Authorization : Bearer ${API_KEY}`
    })
    .then( matchData =>{
        let matchInfo = matchData.data.data
        console.log(matchInfo)
        res.render('matches/match', {matchInfo})    
    
    })

})



// DEVELOP !!!!!!! TEST!!!!!!

module.exports = router;
